export const sliderOnboard = [
  {
    id: 1,
    name: "Run",
    description: "Run and earn with our app. Some text Example will be here",
  },
  {
    id: 2,
    name: "Jump",
    description: "Jump and run with our app. Some text Example will be here",
  },
  {
    id: 3,
    name: "Sleep",
    description: "Sleep and earn with our app. Some text Example will be here",
  },
];

export const activityHistory = [
  {
    id: 1,
    date: "25 jan",
    time: 60,
    numberOfSteps: 1234,
    distance: 10,
    weight: 80,
    calories: 250,
    heartBeat: 120,
  },
  {
    id: 2,
    date: "26 jan",
    time: 30,
    numberOfSteps: 1331,
    distance: 11,
    weight: 80,
    calories: 260,
    heartBeat: 123,
  },
  {
    id: 3,
    date: "27 jan",
    time: 60,
    numberOfSteps: 1234,
    distance: 10,
    weight: 80,
    calories: 250,
    heartBeat: 120,
  },
  {
    id: 4,
    date: "28 jan",
    time: 30,
    numberOfSteps: 1331,
    distance: 11,
    weight: 80,
    calories: 260,
    heartBeat: 123,
  },
  {
    id: 5,
    date: "29 jan",
    time: 60,
    numberOfSteps: 1234,
    distance: 10,
    weight: 80,
    calories: 250,
    heartBeat: 120,
  },
  {
    id: 6,
    date: "26 feb",
    time: 30,
    numberOfSteps: 1331,
    distance: 11,
    weight: 80,
    calories: 260,
    heartBeat: 123,
  },
  {
    id: 7,
    date: "27 feb",
    time: 60,
    numberOfSteps: 1234,
    distance: 10,
    weight: 80,
    calories: 250,
    heartBeat: 120,
  },
  {
    id: 8,
    date: "28 feb",
    time: 30,
    numberOfSteps: 1331,
    distance: 11,
    weight: 80,
    calories: 260,
    heartBeat: 123,
  },
  {
    id: 9,
    date: "25 jan",
    time: 60,
    numberOfSteps: 1234,
    distance: 10,
    weight: 80,
    calories: 250,
    heartBeat: 120,
  },
  {
    id: 10,
    date: "26 jan",
    time: 30,
    numberOfSteps: 1331,
    distance: 11,
    weight: 80,
    calories: 260,
    heartBeat: 123,
  },
];

export const storeData = {
  filterTypes: [
    { id: 1, title: "New", url: require("../../assets/images/card.png") },
    { id: 2, title: "Men", url: require("../../assets/images/coin.png") },
    {
      id: 3,
      title: "Women",
      url: require("../../assets/images/Avatar.png"),
    },
    {
      id: 4,
      title: "Kids",
      url: require("../../assets/images/user.png"),
    },
    {
      id: 5,
      title: "Equip",
      url: require("../../assets/images/routing.png"),
    },
    {
      id: 6,
      title: "Nutrition",
      url: require("../../assets/images/cup.png"),
    },
    {
      id: 7,
      title: "New2",
      url: require("../../assets/images/bank.png"),
    },
    {
      id: 8,
      title: "New3",
      url: require("../../assets/images/Avatar.png"),
    },
  ],
  specials: [
    {
      id: 1,
      headline: "Today’s Special",
      caption: "Get 2x point for every steps, only valid for today",
      points: 2,
      color: "#F45C43",
      url: require("../../assets/images/OBJECTS.png"),
    },
    {
      id: 2,
      headline: "Only Tomorrow",
      caption: "Get 3x point for every steps, only valid for tomorrow",
      points: 3,
      color: "pink",
      url: require("../../assets/images/OBJECTS.png"),
    },
  ],
};
